### ISSUE TITLE
你好 问下AB cip这个项目缺失的文件。

### ISSUE THREAD

**Issue by xiayan830903** [wqliceman/ab_plc_cip_net#1]
你好，问下ABcip这个项目里的ab_cip_comm.c和dynstr.c这两个引用是做啥的，项目下载下来没这两个文件报错

**Comment by wqliceman** [comment]
没有用了，直接删除即可

**Comment by xiayan830903** [comment]
好的，多谢多谢

**Comment by xiayan830903** [comment]
你好，问下样例代码读不出来PLC数据咋回事，能否指点一二。多谢

**Comment by xiayan830903** [comment]
我把写PLC的代码都注释掉了。只保留了读的部分

**Comment by wqliceman** [comment]
我这边测试的AB是1756 ControlLogix。具体你自己用设备研究下吧

**Comment by xiayan830903** [comment]
好的，谢谢

**Comment by songyibao** [comment]
> 你好，问下样例代码读不出来PLC数据咋回事，能否指点一二。多谢

您好，我也是能写入数据但是都读不出来，请问您解决了吗

**Comment by wqliceman** [comment]
> > 你好，问下样例代码读不出来PLC数据咋回事，能否指点一二。多谢
> 
> 您好，我也是能写入数据但是都读不出来，请问您解决了吗

最新版本还有这问题吗？可以调试下看看返回错误码什么的。

**Comment by songyibao** [comment]
> > > 你好，问下样例代码读不出来PLC数据咋回事，能否指点一二。多谢
> > 
> > 
> > 您好，我也是能写入数据但是都读不出来，请问您解决了吗
> 
> 最新版本还有这问题吗？可以调试下看看返回错误码什么的。

使用的是 git clone下来的最新版本, 抓包看了数据，针对于标签```"i32"```进行重复两次先写后读, 可以看到写入操作的响应包( Packet 454 )的状态码为```Success```，而读取操作的响应包( Packet 458 )的状态码为```Unknown Response ( 0xff )```，网上没有查到相关的问题
<img width="1920" alt="截屏2024-05-07 13 49 34" src="https://github.com/s-pms/ab_plc_cip_net/assets/69288039/8c6effe4-73c4-4005-bb81-2a14b55ded44">

**Comment by wqliceman** [comment]
> > > > 你好，问下样例代码读不出来PLC数据咋回事，能否指点一二。多谢
> > > 
> > > 
> > > 您好，我也是能写入数据但是都读不出来，请问您解决了吗
> > 
> > 
> > 最新版本还有这问题吗？可以调试下看看返回错误码什么的。
> 
> 使用的是 git clone下来的最新版本, 抓包看了数据，针对于标签`"i32"`进行重复两次先写后读, 可以看到写入操作的响应包( Packet 454 )的状态码为`Success`，而读取操作的响应包( Packet 458 )的状态码为`Unknown Response ( 0xff )`，网上没有查到相关的问题 <img alt="截屏2024-05-07 13 49 34" width="1920" src="https://private-user-images.githubusercontent.com/69288039/328405393-8c6effe4-73c4-4005-bb81-2a14b55ded44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzQ5NzQsIm5iZiI6MTcxNTA3NDY3NCwicGF0aCI6Ii82OTI4ODAzOS8zMjg0MDUzOTMtOGM2ZWZmZTQtNzNjNC00MDA1LWJiODEtMmExNGI1NWRlZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA5Mzc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NjRjNzEyMTMyOTVmMzU0NmIyNzcwMTkzNzkwZTQ4ZWM0NTJjM2JiMzFmOTRhZDM0NjY5NWY0NzcwOGRhZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2L-0LISZD7efFceQp7W_qoxdr-ZKm2xRBRtwyq78uhM">

你的PLC型号是多少？也可以找个工具测试下是否真实写入成功？
目前我身边没有物理PLC测试，不太好调试

**Comment by wqliceman** [comment]
> > > > > 你好，问下样例代码读不出来PLC数据咋回事，能否指点一二。多谢
> > > > 
> > > > 
> > > > 您好，我也是能写入数据但是都读不出来，请问您解决了吗
> > > 
> > > 
> > > 最新版本还有这问题吗？可以调试下看看返回错误码什么的。
> > 
> > 
> > 使用的是 git clone下来的最新版本, 抓包看了数据，针对于标签`"i32"`进行重复两次先写后读, 可以看到写入操作的响应包( Packet 454 )的状态码为`Success`，而读取操作的响应包( Packet 458 )的状态码为`Unknown Response ( 0xff )`，网上没有查到相关的问题 <img alt="截屏2024-05-07 13 49 34" width="1920" src="https://private-user-images.githubusercontent.com/69288039/328405393-8c6effe4-73c4-4005-bb81-2a14b55ded44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzQ5NzQsIm5iZiI6MTcxNTA3NDY3NCwicGF0aCI6Ii82OTI4ODAzOS8zMjg0MDUzOTMtOGM2ZWZmZTQtNzNjNC00MDA1LWJiODEtMmExNGI1NWRlZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA5Mzc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NjRjNzEyMTMyOTVmMzU0NmIyNzcwMTkzNzkwZTQ4ZWM0NTJjM2JiMzFmOTRhZDM0NjY5NWY0NzcwOGRhZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2L-0LISZD7efFceQp7W_qoxdr-ZKm2xRBRtwyq78uhM">
> 
> 你的PLC型号是多少？也可以找个工具测试下是否真实写入成功？ 目前我身边没有物理PLC测试，不太好调试

同时，你这个标签地址“i32” 你读写的是什么类型？会不会是数据类型错误了呢？

**Comment by songyibao** [comment]
> > > > > > 你好，问下样例代码读不出来PLC数据咋回事，能否指点一二。多谢
> > > > > 
> > > > > 
> > > > > 您好，我也是能写入数据但是都读不出来，请问您解决了吗
> > > > 
> > > > 
> > > > 最新版本还有这问题吗？可以调试下看看返回错误码什么的。
> > > 
> > > 
> > > 使用的是 git clone下来的最新版本, 抓包看了数据，针对于标签`"i32"`进行重复两次先写后读, 可以看到写入操作的响应包( Packet 454 )的状态码为`Success`，而读取操作的响应包( Packet 458 )的状态码为`Unknown Response ( 0xff )`，网上没有查到相关的问题 <img alt="截屏2024-05-07 13 49 34" width="1920" src="https://private-user-images.githubusercontent.com/69288039/328405393-8c6effe4-73c4-4005-bb81-2a14b55ded44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzQ5NzQsIm5iZiI6MTcxNTA3NDY3NCwicGF0aCI6Ii82OTI4ODAzOS8zMjg0MDUzOTMtOGM2ZWZmZTQtNzNjNC00MDA1LWJiODEtMmExNGI1NWRlZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA5Mzc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NjRjNzEyMTMyOTVmMzU0NmIyNzcwMTkzNzkwZTQ4ZWM0NTJjM2JiMzFmOTRhZDM0NjY5NWY0NzcwOGRhZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2L-0LISZD7efFceQp7W_qoxdr-ZKm2xRBRtwyq78uhM">
> > 
> > 
> > 你的PLC型号是多少？也可以找个工具测试下是否真实写入成功？ 目前我身边没有物理PLC测试，不太好调试
> 
> 同时，你这个标签地址“i32” 你读写的是什么类型？会不会是数据类型错误了呢？

写入是可以看到成功了的，我使用的就是物理plc设备，型号是 AB的L82es，```"i32"```标签类型是```DINT```,函数使用的是```ab_cip_write_int32```和```ab_cip_read_int32```，用Studio5000软件连接plc可以实时地看到写入成功。另外，我使用这个库[libplctag](https://github.com/libplctag/libplctag)试了，读写正常。我觉得可能是因为这个plc的CIP协议和一般协议有些不一样吧，我刚接触这块，没有查阅到相关协议的说明
![截屏2024-05-07 21 32 20](https://github.com/s-pms/ab_plc_cip_net/assets/69288039/08743e33-26ba-4baf-a88c-9d112c46fc71)
<img width="797" alt="截屏2024-05-07 21 34 29" src="https://github.com/s-pms/ab_plc_cip_net/assets/69288039/8e12f4e1-bb40-40da-8dbc-405e217d69e1">

**Comment by wqliceman** [comment]
> > > > > > > 你好，问下样例代码读不出来PLC数据咋回事，能否指点一二。多谢
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > 您好，我也是能写入数据但是都读不出来，请问您解决了吗
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 最新版本还有这问题吗？可以调试下看看返回错误码什么的。
> 
> > > > 
> 
> > > > 
> 
> > > > 使用的是 git clone下来的最新版本, 抓包看了数据，针对于标签`"i32"`进行重复两次先写后读, 可以看到写入操作的响应包( Packet 454 )的状态码为`Success`，而读取操作的响应包( Packet 458 )的状态码为`Unknown Response ( 0xff )`，网上没有查到相关的问题 <img alt="截屏2024-05-07 13 49 34" width="1920" src="https://private-user-images.githubusercontent.com/69288039/328405393-8c6effe4-73c4-4005-bb81-2a14b55ded44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzQ5NzQsIm5iZiI6MTcxNTA3NDY3NCwicGF0aCI6Ii82OTI4ODAzOS8zMjg0MDUzOTMtOGM2ZWZmZTQtNzNjNC00MDA1LWJiODEtMmExNGI1NWRlZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA5Mzc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NjRjNzEyMTMyOTVmMzU0NmIyNzcwMTkzNzkwZTQ4ZWM0NTJjM2JiMzFmOTRhZDM0NjY5NWY0NzcwOGRhZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2L-0LISZD7efFceQp7W_qoxdr-ZKm2xRBRtwyq78uhM">
> 
> > > 
> 
> > > 
> 
> > > 你的PLC型号是多少？也可以找个工具测试下是否真实写入成功？ 目前我身边没有物理PLC测试，不太好调试
> 
> > 
> 
> > 同时，你这个标签地址“i32” 你读写的是什么类型？会不会是数据类型错误了呢？
> 
> 
> 
> 写入是可以看到成功了的，我使用的就是物理plc设备，型号是 AB的L82es，```"i32"```标签类型是```DINT```,函数使用的是```ab_cip_write_int32```和```ab_cip_read_int32```，用Studio5000软件连接plc可以实时地看到写入成功。另外，我使用这个库[libplctag](https://github.com/libplctag/libplctag)试了，读写正常。我觉得可能是因为这个plc的CIP协议和一般协议有些不一样吧，我刚接触这块，没有查阅到相关协议的说明
> 
> ![截屏2024-05-07 21 32 20](https://github.com/s-pms/ab_plc_cip_net/assets/69288039/08743e33-26ba-4baf-a88c-9d112c46fc71)
> 
> <img width="797" alt="截屏2024-05-07 21 34 29" src="https://github.com/s-pms/ab_plc_cip_net/assets/69288039/8e12f4e1-bb40-40da-8dbc-405e217d69e1">
> 
> 

你好，我提交了一个版本，麻烦有空的时候物理 plc 上测试一下。谢谢

**Comment by songyibao** [comment]
> > > > > > > > 你好，问下样例代码读不出来PLC数据咋回事，能否指点一二。多谢
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > > > 您好，我也是能写入数据但是都读不出来，请问您解决了吗
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > 最新版本还有这问题吗？可以调试下看看返回错误码什么的。
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 使用的是 git clone下来的最新版本, 抓包看了数据，针对于标签`"i32"`进行重复两次先写后读, 可以看到写入操作的响应包( Packet 454 )的状态码为`Success`，而读取操作的响应包( Packet 458 )的状态码为`Unknown Response ( 0xff )`，网上没有查到相关的问题 <img alt="截屏2024-05-07 13 49 34" width="1920" src="https://private-user-images.githubusercontent.com/69288039/328405393-8c6effe4-73c4-4005-bb81-2a14b55ded44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzQ5NzQsIm5iZiI6MTcxNTA3NDY3NCwicGF0aCI6Ii82OTI4ODAzOS8zMjg0MDUzOTMtOGM2ZWZmZTQtNzNjNC00MDA1LWJiODEtMmExNGI1NWRlZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA5Mzc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NjRjNzEyMTMyOTVmMzU0NmIyNzcwMTkzNzkwZTQ4ZWM0NTJjM2JiMzFmOTRhZDM0NjY5NWY0NzcwOGRhZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2L-0LISZD7efFceQp7W_qoxdr-ZKm2xRBRtwyq78uhM">
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 你的PLC型号是多少？也可以找个工具测试下是否真实写入成功？ 目前我身边没有物理PLC测试，不太好调试
> > 
> > 
> > > 
> > 
> > 
> > > 同时，你这个标签地址“i32” 你读写的是什么类型？会不会是数据类型错误了呢？
> > 
> > 
> > 写入是可以看到成功了的，我使用的就是物理plc设备，型号是 AB的L82es，`"i32"`标签类型是`DINT`,函数使用的是`ab_cip_write_int32`和`ab_cip_read_int32`，用Studio5000软件连接plc可以实时地看到写入成功。另外，我使用这个库[libplctag](https://github.com/libplctag/libplctag)试了，读写正常。我觉得可能是因为这个plc的CIP协议和一般协议有些不一样吧，我刚接触这块，没有查阅到相关协议的说明
> > ![截屏2024-05-07 21 32 20](https://private-user-images.githubusercontent.com/69288039/328543294-08743e33-26ba-4baf-a88c-9d112c46fc71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzUwNTgsIm5iZiI6MTcxNTE3NDc1OCwicGF0aCI6Ii82OTI4ODAzOS8zMjg1NDMyOTQtMDg3NDNlMzMtMjZiYS00YmFmLWE4OGMtOWQxMTJjNDZmYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDEzMjU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjOGM3MGM2ZTk3NzQ0OTkyNDBlZWUxZjQwNzA4NDAwOTJhODE3OWZlMjlkNWViM2YxM2VhOWUzNTMzNDgxZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fEAkmF4F25uddlVhfHXRQBFGNfCGHlvifGyBbdSM9dw)
> > <img alt="截屏2024-05-07 21 34 29" width="797" src="https://private-user-images.githubusercontent.com/69288039/328543543-8e12f4e1-bb40-40da-8dbc-405e217d69e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzUwNTgsIm5iZiI6MTcxNTE3NDc1OCwicGF0aCI6Ii82OTI4ODAzOS8zMjg1NDM1NDMtOGUxMmY0ZTEtYmI0MC00MGRhLThkYmMtNDA1ZTIxN2Q2OWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDEzMjU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNDQzYjZhOGY4OWJjYjNmMDk1ZDllZTAyY2NhZmNjNDU4MTc1ZjFjODdhN2EyNGFmM2U4ZGQ2YTk0YWMyMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LTPCssZOlZ4s5FwNbxsdfYIXBweKUmWeR2z2B650hjA">
> 
> 你好，我提交了一个版本，麻烦有空的时候物理 plc 上测试一下。谢谢

你好，测试过了，除了字符串读写可能还有些问题，其他类型都可以了（这里显示字符串写入成功，实际上从studio5000中可以看到没有写入成功，plc内标签类型为string）
![PixPin_2024_05_08_21_23](https://github.com/s-pms/ab_plc_cip_net/assets/69288039/3784a718-bef0-4abf-b846-ea2f446eecff)

**Comment by wqliceman** [comment]
> stu

好呢，谢谢，我这边再找找资料，研究下字符串读写问题

**Comment by wqliceman** [comment]
> 也是能写入数据但是都读不出来，请问您解决了吗

你更新下最新代码，应该解决了读取问题；字符串写入目前还有点问题，待我再找找方法
