### ISSUE TITLE
Hello, there is still a problem with the string reading method. The string cannot be written in and cannot be read out

### ISSUE THREAD

**Issue by chenglianshu** [wqliceman/ab_plc_cip_net#3]
Hello, there is still a problem with the string reading method. The string cannot be written in and cannot be read out

**Comment by chenglianshu** [comment]
![test result](https://github.com/wqliceman/ab_plc_cip_net/assets/100330385/ee421d5d-4cb2-4606-8346-5d53510ac838)
Dude, sorry to bother you. I tried to write a string and read it, but the result is as shown in the picture. 123456 did not write successfully and the read string is NULL

**Comment by wqliceman** [comment]
> Hello, there is still a problem with the string reading method. The string cannot be written in and cannot be read out

Hi，This bug has been fixed, and read & write string method  are now normal.

**Comment by chenglianshu** [comment]
Okay, thank you very much for replying to me and resolving my doubts. I would like to express my gratitude again. Thank you very much

**Comment by wqliceman** [comment]
You're welcome, I'm very happy to solve your problem
