### ISSUE TITLE
Hello, Dude. Sorry to bother you, but there is still a problem with the write string function, and I have also discovered a new issue regarding the read double type function

### ISSUE THREAD

**Issue by chenglianshu** [wqliceman/ab_plc_cip_net#4]
![test result](https://github.com/wqliceman/ab_plc_cip_net/assets/100330385/7edd2db1-eb15-418d-9f6a-74166669637d)
Hello,Dude. I'm sorry to bother you again. I tested the new code and found that reading the string is normal, but I found that writing the string still has no effect. As shown in the picture, I also discovered a new problem where the double type reading function is not working. I tried to solve it, but I found that I couldn't solve it

**Comment by wqliceman** [comment]
I tried to solve it. Read_string and write_string are completed. Double reading and writing require you to test different addresses. Currently, I don’t have a physical PLC around me. So it cannot be guaranteed to be completely correct.
use tag :v0.0.3

**Comment by wqliceman** [comment]
![image](https://github.com/wqliceman/ab_plc_cip_net/assets/4657009/b60d5131-c910-4043-b31a-a68d968c688a)

**Comment by wqliceman** [comment]
<img width="446" alt="Snipaste_2024-04-09_11-13-03" src="https://github.com/wqliceman/ab_plc_cip_net/assets/4657009/f52c3517-732b-48d2-9378-79dbeb22b6e3">

**Comment by chenglianshu** [comment]
Hello, Dude. Thank you very much for your help. Once again, you helped me solve this problem. Thank you for taking the time to help me solve the problem. Thank you very much

**Comment by abcdvbnmwqeqe** [comment]
我靠( ‵o′)凸，原来还有国际友人用这个，大佬真牛逼
