### ISSUE TITLE
大佬，写入中文字符串有问题，读出来是乱码

### ISSUE THREAD

**Issue by abcdvbnmwqeqe** [wqliceman/ab_plc_cip_net#5]
![1712800471214](https://github.com/wqliceman/ab_plc_cip_net/assets/166672630/535bab40-dbfd-4836-8bb6-97545b326e29)
大佬，你好呀，我今天把代码拉下来用了一下，发现我只要写入中文字符串就会读取出来是乱码就是图片那种???，不知道什么原因，不过大佬真的是我的救星啊，因为我的毕业设计要弄这个东西

**Comment by wqliceman** [comment]
> ![1712800471214](https://github.com/wqliceman/ab_plc_cip_net/assets/166672630/535bab40-dbfd-4836-8bb6-97545b326e29)
> 
> 大佬，你好呀，我今天把代码拉下来用了一下，发现我只要写入中文字符串就会读取出来是乱码就是图片那种???，不知道什么原因，不过大佬真的是我的救星啊，因为我的毕业设计要弄这个东西

这个不支持中文，支持中文就很麻烦了

**Comment by wqliceman** [comment]
> ![1712800471214](https://private-user-images.githubusercontent.com/166672630/321459610-535bab40-dbfd-4836-8bb6-97545b326e29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODc4NzgsIm5iZiI6MTcxMjg4NzU3OCwicGF0aCI6Ii8xNjY2NzI2MzAvMzIxNDU5NjEwLTUzNWJhYjQwLWRiZmQtNDgzNi04YmI2LTk3NTQ1YjMyNmUyOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwMjA2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODk0MjVkYzk0Mzc2Y2MyYjQ1Mzk4NTVjMWE2YzAyYmI4MjllOGZlNTlmYzU5NGE1ZWM5OWQzYWE5MTI5M2E4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jUqNJCiK-egJnNjOegZpA_QKBtu0EANOgDNXkBLRjxQ) 大佬，你好呀，我今天把代码拉下来用了一下，发现我只要写入中文字符串就会读取出来是乱码就是图片那种???，不知道什么原因，不过大佬真的是我的救星啊，因为我的毕业设计要弄这个东西

你也可以自己修改下代码commit下，通过将中文转码为byte数组，进行读写；这个现阶段我就不增加了

**Comment by abcdvbnmwqeqe** [comment]
![图片](https://github.com/wqliceman/ab_plc_cip_net/assets/166672630/9d16dae6-147a-45a9-8913-fc2e11a0f6b8)
大佬，我有点懵，请问是不是改这两个方法

**Comment by wqliceman** [comment]
> ![图片](https://private-user-images.githubusercontent.com/166672630/321844497-9d16dae6-147a-45a9-8913-fc2e11a0f6b8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NzM1ODYsIm5iZiI6MTcxMjk3MzI4NiwicGF0aCI6Ii8xNjY2NzI2MzAvMzIxODQ0NDk3LTlkMTZkYWU2LTE0N2EtNDVhOS04OTEzLWZjMmUxMWEwZjZiOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QwMTU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGIwNGNiNTY1MmU5MzE2MzE2NWM2NjlkOWRlY2Y5NmE2NWRhZmM5NWQ2NGVmZWU2YTQ1MzcyYTM1OWZlM2M2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SJ6wIB2hB-mV1yZXD3lcGf3vgtJJT-kppWfBU1RonhU) 大佬，我有点懵，请问是不是改这两个方法
增加两个新方法，操作UTF-8字符串：
1. 将中文转成byte数值
2. 参照ab_cip_write_string方法写入byte数组
3. 读取字符串的时候，先读取byte数组，再转成中文
（中文处理，我这边平时也使用少，没有深入去研究，如果你完成后，欢迎commit代码）
![1712974060611_d](https://github.com/wqliceman/ab_plc_cip_net/assets/4657009/581efbc4-4f77-47c6-aff2-26d61b5388be)

**Comment by abcdvbnmwqeqe** [comment]
![中文字符串问题](https://github.com/wqliceman/ab_plc_cip_net/assets/166672630/19914a5f-f936-41df-a924-e41dd9716b8b)
大佬，我把中文字符串改成byte数组好像也不行，而且我把其他类型的读写顺序换了一下，然后有符号，和无符号类型读取出来的值被后面写的覆盖了
![类型读取问题](https://github.com/wqliceman/ab_plc_cip_net/assets/166672630/7eebc052-9fec-4e33-bbf8-9a806cd9b2bc)
